### ISSUE TITLE
Cell map and clustering

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#10]
Move the tSNE map to the top of the page. and place the QC controls (dispersion and silhouette) below

**Comment by katsikora** [comment]
The risk is the users will then be less motivated to inspect the QC plots.

**Comment by thomasmanke** [comment]
Well, I was worried that the users will be less motivated to inspect the tSNE plot :-)
Currently it is not explained what to look for. Silhouette scores should be close to 1, but I struggle to interpret the cluster dispersion. Those plots may provide additional guidance to justify a certain number of clusters, but I don't think they have precedence over the tSNE plot in this explorative setting.

**Comment by katsikora** [comment]
This is now implemented.
