### ISSUE TITLE
separate dim.red choice from clustering and provide UMAP support

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#11]
dim reduction method only offers tSNE at the moment.

Selecting the dim reduction should be independent from clustering, so these two choices should be separate before updating the cluster plot.

**Comment by katsikora** [comment]
For Monocle2 and RaceID3, currenlty only the tSNE coordinates are available. For Seurat3, also UMAP is available. 
There is no recalculation of the coordinates by the app, only the slot used to plot the cell map is switched. It's on the same plot control box, as it applies changes to the same plot as changing the number of clusters.
