### ISSUE TITLE
selection of multiple genes

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#15]
I could not find any description of what happens when multiple genes are selected.
I assume some sum or average, but this is not described. It would be good to have a notice also next to the selection panel - not just the vignette.

**Comment by katsikora** [comment]
This information  available in the following places:
- Method Description in the "Marker Gene Visualization" tab (updated)
- Method Description in the "Correlation Analyses" tab  - 2 instances, each for one plot
