### ISSUE TITLE
dispersion plot does not recalculate if number of clusters is changed

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#16]
Instead an error is returned, if the number of clusters is changed from default.
Even resetting to the default (in the example: 6) will not recalculate the "clustree" plot.

Error: run cluster before plotsaturation

**Comment by katsikora** [comment]
which package are you referring to Thomas? RaceID or Seurat?

**Comment by katsikora** [comment]
This is now fixed.

**Comment by thomasmanke** [comment]
I have tested only RaceID sofar.
