### ISSUE TITLE
clarify dependencies in README.md

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#18]
the dependencies are not properly documented.
best to include aux.R in the repo and state explicitly the dependencies from Rlib.

**Comment by thomasmanke** [comment]
Since you are counting non-zero entries

summary(colSums(as.matrix(ndata)))

should probably be

summary(colSums(as.matrix(ndata)>0))

**Comment by katsikora** [comment]
- aux.R is included in the repo
- why do we care to document the dependencies? this is for inhouse use only, i.e. there are several places where our internal paths are stated (e.g. Rlib, paths in the Dockerfile, setup.py etc)
- zeroes don't change the sum

**Comment by thomasmanke** [comment]
-but I have communicated the github link with outside people too.

**Comment by thomasmanke** [comment]
- wrong place for this issue, but (>0) will change the behaviour, because it causes counting not summing the values.

**Comment by katsikora** [comment]
I've listed the R packages in the Readme.

Can you please repost in the other issue? I'm closing this one.
