### ISSUE TITLE
Pressing "submit data" set too early results in crash

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#19]
It is important to press "Submit dataset" only _after_ "Finishing upload" is complete.
Otherwise I managed to crash the service.
One should alert the user, especially since the crash is not obvious/not reported.

**Comment by katsikora** [comment]
It's in the vignette, e,g, "Upload the dataset (wait until complete) and click on ‘Select dataset’ (Figure 1)."

**Comment by katsikora** [comment]
the 'Submit dataset' button is now hidden until the file upload is complete
