### ISSUE TITLE
QC metrics missing for Seurat

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#22]
I believe you want to show the Elbowplot (as for RaceID). Perhaps even another metrics. It looks as 3 plot areas are prepared, but only the Silhouette Plot is shown.

**Comment by katsikora** [comment]
As discussed (and documented in the vignette), the clustree plot will remain blank until several clustering rounds with different resolutions have been run on the dataset.
I don't get this extra area with Firefox 68.0.2  under Linux.

**Comment by katsikora** [comment]
I've fixed this display bug, it was affecting the ui on the Mac.
