### ISSUE TITLE
Top.Correl.Genes

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#3]
Not sure if it is meaningful to show the distribution of (all) correlation coefficients in "Top.Correla.Genes" - perhaps a heatmap of the top 10 correlated genes over the clusters would be more informative?

**Comment by thomasmanke** [comment]
... or a pair() plot of the top10?

**Comment by katsikora** [comment]
- The distribution is provided to visualize to the user if a gene has any highly correlated genes or not. Ideally, there should be a couple of strong outliers in the higher correlation range. If all the coefs are low, say <0.3, then top10 are not very informative.

- A violin plot might be a somewhat better representation than the currently available boxplot.

- The user might inspect pairwise expression values after providing the necessary information for the plot designed for this purpose.

- As to visualizing expression of correlated genes on a tsne map, I'm considering adding an extention that would produce gene modules. This would take care of pruning 'weak' correlations or sparse modules etc.

**Comment by katsikora** [comment]
Violin plot is implemented.
