### ISSUE TITLE
Select multiple genes

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#5]
Need to clarify better how to specify multiple genes for tSNE visualisation and pairwise. expression. I assume its comma or space separators, but it did not work.

**Comment by katsikora** [comment]
"GeneID: Please provide a semicolon-separated list of Gene IDs you would like to obtain results for."

As stated on the side bar right below the  GeneID field. 
It is missing for  Pairwise expression, I will add it there (the same applies).

**Comment by thomasmanke** [comment]
does not work in "Pairwise.Expression"

**Comment by thomasmanke** [comment]
it's also not documented how ";" is interpreted. Sum, Average, max, ... ?

**Comment by thomasmanke** [comment]
Ok, I sort of found it in the output
"(Log) counts were aggregated over selected genes and the expression levels were colour-coded on the tsne map."

**Comment by katsikora** [comment]
I will document it more clearly, it's sum. Also, I skipped this  case in the vignette.

**Comment by thomasmanke** [comment]
I think the gene selection should really be part of "Plot Controls"

**Comment by katsikora** [comment]
All implemented.
