### ISSUE TITLE
smooth exit for wrong input formats

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/scRNAseq_shiny_app#7]
If a file cannot be read properly, I would prefer a smooth exit, with some sort of alert:
"Please double check whether file exists, is non-empty and has the proper format"

**Comment by katsikora** [comment]
Format and slot checks were added.
The check for existing file was not implemented as the only available option to provide one is currently file upload. Thus, the file has to be found in the browser. If it's empty, the class check should fail (not tested).
